using BusinessFinance.Api.Security;
using BusinessFinance.Application.Abstractions.Authentication;
using BusinessFinance.Application.Accounts.CreateAccount;
using BusinessFinance.Application.Accounts.DeleteAccount;
using BusinessFinance.Application.Accounts.DeactivateAccount;
using BusinessFinance.Application.Accounts.GetAccount;
using BusinessFinance.Application.Accounts.ListAccounts;
using BusinessFinance.Application.Accounts.UpdateAccount;
using BusinessFinance.Application.Categories;
using BusinessFinance.Application.Transactions;
using BusinessFinance.Application.Budgets;
using BusinessFinance.Application.Profiles;
using BusinessFinance.Application.Reports;
using BusinessFinance.Application.Authentication.LoginUser;
using BusinessFinance.Application.Authentication.Logout;
using BusinessFinance.Application.Authentication.RefreshTokens;
using BusinessFinance.Application.Authentication.RegisterUser;
using BusinessFinance.Application.UserAccount;
using BusinessFinance.Application.Verification;
using BusinessFinance.Application.Transfers;
using BusinessFinance.Application.CreditCards;
using BusinessFinance.Application.Counterparties;
using BusinessFinance.Application.RecurringTransactions;
using BusinessFinance.Application.Taxes;
using BusinessFinance.Application.UpcomingPayments;
using BusinessFinance.Application.DataPortability;
using BusinessFinance.Application.Debts;
using BusinessFinance.Application.SavingsGoals;
using BusinessFinance.Application.Attachments;
using BusinessFinance.Application.FinancialActivities;
using BusinessFinance.Application.Imports;
using BusinessFinance.Application.Receipts;
using BusinessFinance.Application.Cash;
using BusinessFinance.Application.Obligations;
using BusinessFinance.Application.Pos;

namespace BusinessFinance.Api.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApplicationUseCases(
        this IServiceCollection services)
    {
        services.AddHttpContextAccessor();
        services.AddScoped<ICurrentUser, HttpContextCurrentUser>();
        services.AddTransient<RegisterUserUseCase>();
        services.AddTransient<LoginUserUseCase>();
        services.AddTransient<RefreshTokensUseCase>();
        services.AddTransient<LogoutUseCase>();
        services.AddTransient<GetUserAccountUseCase>();
        services.AddTransient<ListUserSessionsUseCase>();
        services.AddTransient<RevokeUserSessionUseCase>();
        services.AddTransient<ChangePasswordUseCase>();
        services.AddTransient<DeleteUserAccountUseCase>();
        services.AddTransient<SendEmailVerificationUseCase>();
        services.AddTransient<ConfirmEmailUseCase>();
        services.AddTransient<RequestPasswordResetUseCase>();
        services.AddTransient<ResetPasswordUseCase>();
        services.AddTransient<CreateAccountUseCase>();
        services.AddTransient<DeleteAccountUseCase>();
        services.AddTransient<ListAccountsUseCase>();
        services.AddTransient<GetAccountUseCase>();
        services.AddTransient<DeactivateAccountUseCase>();
        services.AddTransient<UpdateAccountUseCase>();
        services.AddTransient<CreateCategoryUseCase>();
        services.AddTransient<ListCategoriesUseCase>();
        services.AddTransient<UpdateCategoryUseCase>();
        services.AddTransient<CreateTransactionUseCase>();
        services.AddTransient<CancelTransactionUseCase>();
        services.AddTransient<ListTransactionsUseCase>();
        services.AddTransient<GetTransactionUseCase>();
        services.AddTransient<CreateBudgetUseCase>();
        services.AddTransient<GetUserProfileUseCase>();
        services.AddTransient<SetUserProfileUseCase>();
        services.AddTransient<UpdateBudgetUseCase>();
        services.AddTransient<ListBudgetsUseCase>();
        services.AddTransient<DeleteBudgetUseCase>();
        services.AddTransient<GetMonthlyReportUseCase>();
        services.AddTransient<GetAdvancedFinancialReportUseCase>();
        services.AddTransient<CreateTransferUseCase>();
        services.AddTransient<GetTransferUseCase>();
        services.AddTransient<ListTransfersUseCase>();
        services.AddTransient<CancelTransferUseCase>();
        services.AddTransient<CreateCounterpartyUseCase>();
        services.AddTransient<UpdateCounterpartyUseCase>();
        services.AddTransient<ListCounterpartiesUseCase>();
        services.AddTransient<GetCounterpartyUseCase>();
        services.AddTransient<DeleteCounterpartyUseCase>();
        services.AddTransient<CreateCounterpartyChargeUseCase>();
        services.AddTransient<CreateCounterpartyPaymentUseCase>();
        services.AddTransient<CancelCounterpartyChargeUseCase>();
        services.AddTransient<CancelCounterpartyPaymentUseCase>();
        services.AddTransient<CreateCreditCardUseCase>();
        services.AddTransient<GetCreditCardUseCase>();
        services.AddTransient<ListCreditCardsUseCase>();
        services.AddTransient<UpdateCreditCardUseCase>();
        services.AddTransient<CreateCardChargeUseCase>();
        services.AddTransient<CreateCardPaymentUseCase>();
        services.AddTransient<ListCardActivityUseCase>();
        services.AddTransient<CancelCardChargeUseCase>();
        services.AddTransient<CancelCardPaymentUseCase>();
        services.AddTransient<GetCreditCardStatementUseCase>();
        services.AddTransient<GetCurrentCreditCardStatementUseCase>();
        services.AddTransient<CreateInstallmentPlanUseCase>();
        services.AddTransient<ListInstallmentPlansUseCase>();
        services.AddTransient<RealizeInstallmentUseCase>();
        services.AddTransient<CreateRecurringTransactionUseCase>();
        services.AddTransient<ListRecurringTransactionsUseCase>();
        services.AddTransient<SetRecurringActiveUseCase>();
        services.AddTransient<GenerateRecurringOccurrencesUseCase>();
        services.AddTransient<ListRecurringOccurrencesUseCase>();
        services.AddTransient<DeleteRecurringTransactionUseCase>();
        services.AddTransient<RealizeRecurringOccurrenceUseCase>();
        services.AddTransient<RealizeDueRecurringUseCase>();
        services.AddTransient<RecurringOccurrenceMaterializer>();
        services.AddTransient<UpdateRecurringTransactionUseCase>();
        services.AddTransient<SetOccurrenceAmountUseCase>();
        services.AddTransient<UndoRecurringOccurrenceUseCase>();
        services.AddTransient<CreateTaxPaymentUseCase>();
        services.AddTransient<UndoTaxPaymentUseCase>();
        services.AddTransient<GetTaxOverviewUseCase>();
        services.AddTransient<CreateTaxPlansUseCase>();
        services.AddTransient<ListTaxPaymentsUseCase>();
        services.AddTransient<GetTaxPlanDetailUseCase>();
        services.AddTransient<ListPlannedActivitiesUseCase>();
        services.AddTransient<ListFinancialActivitiesUseCase>();
        services.AddTransient<GetActivityBalancesUseCase>();
        services.AddTransient<GetUpcomingPaymentsUseCase>();
        services.AddTransient<ExportTransactionsCsvUseCase>();
        services.AddTransient<ExportCounterpartyLedgerCsvUseCase>();
        services.AddTransient<ExportFinancialJsonUseCase>();
        services.AddTransient<CreateBackupUseCase>();
        services.AddTransient<ValidateBackupUseCase>();
        services.AddTransient<RestoreBackupUseCase>();
        services.AddTransient<CreateDebtUseCase>();
        services.AddTransient<ListDebtsUseCase>();
        services.AddTransient<PayDebtInstallmentUseCase>();
        services.AddTransient<RecordDebtOpeningUseCase>();
        services.AddTransient<CreateSavingsGoalUseCase>();
        services.AddTransient<ListSavingsGoalsUseCase>();
        services.AddTransient<AddSavingsGoalContributionUseCase>();
        services.AddTransient<DeleteSavingsGoalUseCase>();
        services.AddTransient<UploadAttachmentUseCase>();
        services.AddTransient<ListAttachmentsUseCase>();
        services.AddTransient<DownloadAttachmentUseCase>();
        services.AddTransient<StageCsvImportUseCase>();
        services.AddTransient<GetImportBatchUseCase>();
        services.AddTransient<UpdateImportCandidateUseCase>();
        services.AddTransient<ConfirmImportBatchUseCase>();
        services.AddTransient<ResolveImportDuplicateUseCase>();
        services.AddTransient<AnalyzeReceiptUseCase>();
        services.AddTransient<CreateObligationUseCase>();
        services.AddTransient<ListObligationsUseCase>();
        services.AddTransient<SettleObligationUseCase>();
        services.AddTransient<GetCashCountTodayUseCase>();
        services.AddTransient<ListCashCountsUseCase>();
        services.AddTransient<CreateCashCountUseCase>();
        services.AddTransient<ConfirmCashCountDifferenceUseCase>();
        services.AddTransient<ListPosSettlementsUseCase>();
        services.AddTransient<CreatePosSettlementUseCase>();
        services.AddTransient<CancelPosSettlementUseCase>();
        services.AddTransient<ListPosDefinitionsUseCase>();
        services.AddTransient<CreatePosDefinitionUseCase>();
        services.AddTransient<UpdatePosDefinitionUseCase>();
        services.AddTransient<SetPosDefinitionActiveUseCase>();
        services.AddTransient<SetDefaultPosDefinitionUseCase>();
        services.AddTransient<DeletePosDefinitionUseCase>();
        services.AddTransient<PreviewPosSettlementUseCase>();
        services.AddTransient<PreviewPosDepositUseCase>();
        services.AddTransient<CreatePosDepositUseCase>();
        services.AddTransient<GetPosDepositUseCase>();
        services.AddTransient<RevertPosDepositUseCase>();

        return services;
    }
}
